name: appsyncmasterclass
schema: schema.api.graphql
authenticationType: AMAZON_COGNITO_USER_POOLS
userPoolConfig: 
  awsRegion: us-east-1
  defaultAction: ALLOW
  userPoolId: !Ref CognitoUserPool
mappingTemplatesLocation: mapping-templates
mappingTemplates: 
  - type: Query 
    field: getMyProfile
    dataSource: usersTable
    # since we follow the proper naming convention for the mapping templates,
    # the request and response parameters aren't required
  
    # request: Query.getMyProfile.request.vtl
    # response: Query.getMyProfile.response.vtl
  - type: Query
    field: getImageUploadUrl
    dataSource: getImageUploadUrlFunction
    request: false
    response: false
  - type: Query
    field: getTweets
    dataSource: tweetsTable
  - type: Query
    field: getMyTimeline
    dataSource: timelinesTable

  - type: Mutation
    field: editMyProfile
    dataSource: usersTable
  - type: Mutation
    field: tweet
    dataSource: tweetFunction
    request: false
    response: false

  # NESTED FIELDS
  - type: Tweet
    field: profile
    dataSource: usersTable
  - type: TimelinePage
    field: tweets
    dataSource: tweetsTable

dataSources:
  - type: NONE
    name: none
  - type: AMAZON_DYNAMODB
    name: usersTable
    config:
      tableName: !Ref UsersTable
  - type: AMAZON_DYNAMODB
    name: tweetsTable
    config:
      tableName: !Ref TweetsTable
  - type: AMAZON_DYNAMODB
    name: timelinesTable
    config:
      tableName: !Ref TimelinesTable
  - type: AWS_LAMBDA
    name: getImageUploadUrlFunction
    config:
      functionName: getImageUploadUrl
  - type: AWS_LAMBDA
    name: tweetFunction
    config:
      functionName: tweet

# Appsync plugin is able to pass the {TweetsTable} argument into the TimelinePage.tweets.request.vtl and extract the actual TweetsTable name
substitutions:
  TweetsTable: !Ref TweetsTable